apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hkbltc-gov-ui
  name: hkbltc-gov-ui
spec:
  containers:
    - name: node
      image: node:10
      command:
        - cat
      tty: true
      volumeMounts:
        - name: yarn-cache-repo
          mountPath: /root/.cache/yarn
    - name: aliyun-tools
      image: registry.cn-shanghai.aliyuncs.com/kycic/aliyun-tools:0.0.1
      command:
        - cat
      tty: true
      volumeMounts:
        - name: oss-config
          mountPath: /root/.ossutilconfig
          subPath: .ossutilconfig
  volumes:
    - name: yarn-cache-repo
      persistentVolumeClaim:
        claimName: yarn-cache-pvc
    - name: oss-config
      secret:
        secretName: oss-config-secret
